<a href="https://colab.research.google.com/github/sarayukammari/ML-Projects/blob/main/Wine_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import datasets

wine= datasets.load_wine(as_frame=True)
x=wine.data
y=wine.target
# first_vs_rest = (y == 0) | (y == 1),(y == 2)
# print(X.head())
# print(y.head())
# print(y.value_counts())
# print(x.value_counts())


In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)


In [ ]:
from sklearn.svm import SVC,LinearSVC
from sklearn.metrics import cross_val_score
from sklearn.pipeline import Pipeline
model=LinearSVC()
model.fit(x_train,y_train)



0.97192118226601
[0.96551724 0.96551724 1.         0.96428571 0.96428571]


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform,loguniform

n_parameters={
    "svc__C": uniform(1,100),
    "svc__gamma":loguniform(0.001,0.1)
}

searchcv= RandomizedSearchCV(model,n_parameters,cv=5,n_iter=100,random_state=42)
searchcv.fit(x_train,y_train)
score=searchcv.score(x_test,y_test)
print(score)


1.0


In [ ]:
from sklearn.metrics import confusion_matrix
y_pred = searchcv.best_estimator_.predict(x_test)
print(confusion_matrix(y_test, y_pred))


[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]


In [ ]:
import numpy as np
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)
print(np.unique(y_test, return_counts=True))


(142, 13) (36, 13)
(142,) (36,)
(array([0, 1, 2]), array([14, 14,  8]))
